# Generated by Django 2.0.7 on 2019-12-12 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('type', models.TextField(max_length=700)),
                ('urgency', models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Not Urgent', 'Not Urgent')], default='', max_length=100, null=True)),
                ('specification', models.CharField(blank=True, choices=[('coloured', 'coloured'), ('not coloured', 'not coloured')], default='', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
